### ISSUE TITLE
Failed to parse line: =65=20=28=42=65=72=6E=61=72=64=29=0A=0A

### ISSUE THREAD

**Issue by MrHappy** [f41c0r/Python-Android-Facebook-Contact-Sync#2]
It shows 3 contacts and then stops with this error:
Traceback (most recent call last):
  File "fb_picture_scrape_add_to_vcard.py", line 81, in <module>
    sys.exit(main(sys.argv))
  File "fb_picture_scrape_add_to_vcard.py", line 64, in main
    for component in components:
  File "D:\Python-Android-Facebook-Contact-Sync-master\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\vobject\base.py", line 1002, in readComponents
    vline = textLineToContentLine(line, n)
  File "D:\Python-Android-Facebook-Contact-Sync-master\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\vobject\base.py", line 859, in textLineToContentLine
    return ContentLine(*parseLine(text, n), **{'encoded':True, 'lineNumber' : n})
  File "D:\Python-Android-Facebook-Contact-Sync-master\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\vobject\base.py", line 727, in parseLine
    raise ParseError("Failed to parse line: %s" % line, lineNumber)
vobject.base.ParseError: At line 919: Failed to parse line: =65=20=28=42=65=72=6E=61=72=64=29=0A=0A

**Comment by f41c0r** [comment]
Go look at your 4th contact and see if you can find anything that seems different about it? I'd ask you to send me a copy of your vcard file so I can see what's going on but that's a violation of your privacy unless you feel comfortable sharing that info with me

**Comment by MrHappy** [comment]
I just did, the weird thing is that it doesn't go through the index.html top-down, looks more like random.
The first contact is first in file, the second is somewhere on line 4000 and the third on line 2000 (not exactly, but roughly)...

**Comment by f41c0r** [comment]
If you want to solve it yourself, my advice to you would be to use pdb, let it break and then examine what line broke it. Otherwise, I can't help without access to the data to debug myself. It sounds to me like Google (surprise) did something nonstandard with their vcf export and vobject doesn't know how to parse that data.

**Comment by MrHappy** [comment]
Found, was looking at the wrong place.. :(
Google split some 'encoded:' lines into 2, and thus let some lines start with '='...

**Comment by f41c0r** [comment]
yep that'll do it
